### PR TITLE
added "Code-Of-Conduct" file

### LINKED ISSUE #4: adding Code-of-Conduct file
This will help contributor to know the rules and regulation for contributing.
Please assign this to me under hacktoberfest 2022. @fdebrain

### PR DESCRIPTION
**Pull request by goodchai0**

### CODE REVIEW

**Comment by fdebrain** [comment]
@goodchai0 thanks for your contribution. Feel free to propose additional improvements in the issues

**Review by fdebrain — APPROVED** [review]
LGTM

**Comment by goodchai0** [comment]
Yes, sure I will open other issues too in future.

**Comment by goodchai0** [comment]
can you add "hacktoberfest-accepted" label too, otherwise the PR wont be counted.

**Pull request merged**
